### ISSUE TITLE
Have you been testing this lately ?

### ISSUE THREAD

**Issue by ghost** [elsampsa/websocket-mse-demo#1]
First of all, thank you very much! This was exactly what I was looking for :)
Sorry, I could'n get it to work.

![ss2](https://user-images.githubusercontent.com/3117195/60305098-08b16e00-992b-11e9-8182-68fd770ad5c9.jpg)

Best regards

**Comment by winkmichael** [comment]
Did you ever get this to work? I ran into "The type provided ('video/mp4') is unsupported in Chrome, and Firefox complains about the character encoding.

**Comment by elsampsa** [comment]
woopsie.. I had this abandoned.  Please see the updated README.md.
